DROP DATABASE CLP;
CREATE DATABASE CLP;
USE CLP;

CREATE TABLE COUNTRY (
    CountryId INT PRIMARY KEY,
    CountryName VARCHAR(100) NOT NULL UNIQUE,
    Continent VARCHAR(100) NOT NULL,
    Currency VARCHAR(50) NOT NULL
);

CREATE TABLE DEPARTMENT (
    DepartmentId INT PRIMARY KEY,
    DeptName VARCHAR(100) NOT NULL,
    CountryId INT NOT NULL,
    FOREIGN KEY (CountryId) REFERENCES COUNTRY(CountryId)
);

CREATE TABLE EMPLOYEE (
    EmpId INT PRIMARY KEY,
    EmpName VARCHAR(100) NOT NULL,
    DeptId INT NOT NULL,
    FOREIGN KEY (DeptId) REFERENCES DEPARTMENT(DepartmentId)
);

CREATE TABLE FOLDER (
    FolderId INT PRIMARY KEY,
    EmpId INT NOT NULL,
    AccessType ENUM('Read','Write','Admin') NOT NULL,
    FOREIGN KEY (EmpId) REFERENCES EMPLOYEE(EmpId)
);


INSERT INTO COUNTRY VALUES (1,'Spain','Europe','Euro');
INSERT INTO COUNTRY VALUES (2,'India','Asia','Rupee');
INSERT INTO COUNTRY VALUES (3,'USA','North America','Dollar');
INSERT INTO COUNTRY VALUES (4,'Egypt','Africa','Pound');
INSERT INTO COUNTRY VALUES (5,'Thailand','Asia','Baht');


INSERT INTO DEPARTMENT VALUES (501,'HR',1);
INSERT INTO DEPARTMENT VALUES (502,'IT',2);
INSERT INTO DEPARTMENT VALUES (503,'Finance',3);
INSERT INTO DEPARTMENT VALUES (504,'Marketing',4);
INSERT INTO DEPARTMENT VALUES (505,'Research',5);


INSERT INTO EMPLOYEE VALUES (6001,'Carlos',501);
INSERT INTO EMPLOYEE VALUES (6002,'Anika',502);
INSERT INTO EMPLOYEE VALUES (6003,'Michael',503);
INSERT INTO EMPLOYEE VALUES (6004,'Omar',504);
INSERT INTO EMPLOYEE VALUES (6005,'Niran',505);


INSERT INTO FOLDER VALUES (31,6001,'Admin');
INSERT INTO FOLDER VALUES (32,6002,'Read');
INSERT INTO FOLDER VALUES (33,6003,'Write');
INSERT INTO FOLDER VALUES (34,6004,'Read');
INSERT INTO FOLDER VALUES (35,6005,'Admin');


DESCRIBE COUNTRY;
DESCRIBE DEPARTMENT;
DESCRIBE EMPLOYEE;
DESCRIBE FOLDER;


SELECT * FROM COUNTRY;
SELECT * FROM DEPARTMENT;
SELECT * FROM EMPLOYEE;
SELECT * FROM FOLDER;
